// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: notificationspb/api.proto

package notificationspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_NotifyOrderCreated_FullMethodName  = "/notificationspb.NotificationService/NotifyOrderCreated"
	NotificationService_NotifyOrderCanceled_FullMethodName = "/notificationspb.NotificationService/NotifyOrderCanceled"
	NotificationService_NotifyOrderReady_FullMethodName    = "/notificationspb.NotificationService/NotifyOrderReady"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	NotifyOrderCreated(ctx context.Context, in *NotifyOrderCreatedRequest, opts ...grpc.CallOption) (*NotifyOrderCreatedResponse, error)
	NotifyOrderCanceled(ctx context.Context, in *NotifyOrderCanceledRequest, opts ...grpc.CallOption) (*NotifyOrderCanceledResponse, error)
	NotifyOrderReady(ctx context.Context, in *NotifyOrderReadyRequest, opts ...grpc.CallOption) (*NotifyOrderReadyResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) NotifyOrderCreated(ctx context.Context, in *NotifyOrderCreatedRequest, opts ...grpc.CallOption) (*NotifyOrderCreatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyOrderCreatedResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyOrderCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotifyOrderCanceled(ctx context.Context, in *NotifyOrderCanceledRequest, opts ...grpc.CallOption) (*NotifyOrderCanceledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyOrderCanceledResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyOrderCanceled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) NotifyOrderReady(ctx context.Context, in *NotifyOrderReadyRequest, opts ...grpc.CallOption) (*NotifyOrderReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyOrderReadyResponse)
	err := c.cc.Invoke(ctx, NotificationService_NotifyOrderReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	NotifyOrderCreated(context.Context, *NotifyOrderCreatedRequest) (*NotifyOrderCreatedResponse, error)
	NotifyOrderCanceled(context.Context, *NotifyOrderCanceledRequest) (*NotifyOrderCanceledResponse, error)
	NotifyOrderReady(context.Context, *NotifyOrderReadyRequest) (*NotifyOrderReadyResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) NotifyOrderCreated(context.Context, *NotifyOrderCreatedRequest) (*NotifyOrderCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyOrderCreated not implemented")
}
func (UnimplementedNotificationServiceServer) NotifyOrderCanceled(context.Context, *NotifyOrderCanceledRequest) (*NotifyOrderCanceledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyOrderCanceled not implemented")
}
func (UnimplementedNotificationServiceServer) NotifyOrderReady(context.Context, *NotifyOrderReadyRequest) (*NotifyOrderReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyOrderReady not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_NotifyOrderCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyOrderCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyOrderCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyOrderCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyOrderCreated(ctx, req.(*NotifyOrderCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotifyOrderCanceled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyOrderCanceledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyOrderCanceled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyOrderCanceled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyOrderCanceled(ctx, req.(*NotifyOrderCanceledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_NotifyOrderReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyOrderReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).NotifyOrderReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_NotifyOrderReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).NotifyOrderReady(ctx, req.(*NotifyOrderReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notificationspb.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyOrderCreated",
			Handler:    _NotificationService_NotifyOrderCreated_Handler,
		},
		{
			MethodName: "NotifyOrderCanceled",
			Handler:    _NotificationService_NotifyOrderCanceled_Handler,
		},
		{
			MethodName: "NotifyOrderReady",
			Handler:    _NotificationService_NotifyOrderReady_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notificationspb/api.proto",
}
